# Generated by Django 5.2.7 on 2025-10-13 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "political_bias",
                    models.CharField(
                        choices=[
                            ("far_left", "Far Left"),
                            ("left", "Left"),
                            ("center_left", "Center Left"),
                            ("center", "Center"),
                            ("center_right", "Center Right"),
                            ("right", "Right"),
                            ("far_right", "Far Right"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "bias_confidence_score",
                    models.FloatField(help_text="Confidence score from 0-1"),
                ),
                (
                    "bias_reasoning",
                    models.TextField(help_text="AI reasoning for bias classification"),
                ),
                (
                    "positive_sentiment",
                    models.FloatField(
                        help_text="Percentage of positive sentiment (0-1)"
                    ),
                ),
                (
                    "negative_sentiment",
                    models.FloatField(
                        help_text="Percentage of negative sentiment (0-1)"
                    ),
                ),
                (
                    "neutral_sentiment",
                    models.FloatField(
                        help_text="Percentage of neutral sentiment (0-1)"
                    ),
                ),
                (
                    "overall_sentiment_score",
                    models.FloatField(help_text="Overall sentiment score (-1 to 1)"),
                ),
                (
                    "primary_topics",
                    models.JSONField(
                        default=list, help_text="List of primary political topics"
                    ),
                ),
                (
                    "topic_distribution",
                    models.JSONField(
                        default=dict, help_text="Topic distribution percentages"
                    ),
                ),
                (
                    "key_themes",
                    models.JSONField(default=list, help_text="Main themes identified"),
                ),
                ("emotional_tone", models.CharField(blank=True, max_length=50)),
                (
                    "controversy_level",
                    models.FloatField(
                        default=0.0, help_text="Controversy level from 0-1"
                    ),
                ),
                ("analysis_version", models.CharField(default="1.0", max_length=10)),
                ("processing_time_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_ai_response",
                    models.JSONField(help_text="Raw response from OpenAI"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_analyses",
                        to="news.newsarticle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sentiment Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("comparison_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_comparisons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "analyses",
                    models.ManyToManyField(
                        related_name="comparisons", to="analysis.sentimentanalysis"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_categories",
                    models.JSONField(
                        default=list, help_text="User's preferred news categories"
                    ),
                ),
                (
                    "notification_settings",
                    models.JSONField(
                        default=dict, help_text="User notification preferences"
                    ),
                ),
                (
                    "default_analysis_depth",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("detailed", "Detailed"),
                            ("comprehensive", "Comprehensive"),
                        ],
                        default="detailed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="sentimentanalysis",
            index=models.Index(
                fields=["user", "-created_at"], name="analysis_se_user_id_b43094_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentimentanalysis",
            index=models.Index(
                fields=["article", "-created_at"], name="analysis_se_article_b4c11e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentimentanalysis",
            index=models.Index(
                fields=["political_bias"], name="analysis_se_politic_08d710_idx"
            ),
        ),
    ]
